steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'frontend-app/Dockerfile'
      - '--build-arg'
      - 'VITE_GCP_API_KEY=${_VITE_GCP_API_KEY}'
      - '--build-arg'
      - 'VITE_API_BASE_URL=${_VITE_API_BASE_URL}'
      - '--build-arg'
      - 'VITE_MARKETING_URL=${_VITE_MARKETING_URL}'
      - '--build-arg'
      - 'VITE_MAINTENANCE_MODE=${_VITE_MAINTENANCE_MODE}'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/jualuma-repo/frontend-app:$BUILD_ID'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/jualuma-repo/frontend-app:latest'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/jualuma-repo/frontend-app:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/jualuma-repo/frontend-app:latest'
options:
  logging: CLOUD_LOGGING_ONLY
