/*
 * Copyright (c) 2026 Intellifide, LLC.
 * Licensed under PolyForm Noncommercial License 1.0.0.
 * See "/legal/license" for full license terms.
 *
 * COMMUNITY RIGHTS:
 * - You CAN modify this code for personal use.
 * - You CAN build and share widgets/plugins for the ecosystem.
 *
 * RESTRICTIONS:
 * - You CANNOT resell, repackage, or distribute this application for a fee.
 * - You CANNOT use this application for commercial enterprise purposes.
 */

import React, { useRef, useState } from 'react';

interface AIPrivacyModalProps {
    onAccept: () => void;
    isOpen: boolean;
    onClose: () => void;
}

export const AIPrivacyModal: React.FC<AIPrivacyModalProps> = ({ onAccept, isOpen, onClose }) => {
    const [canAcceptPrivacy, setCanAcceptPrivacy] = useState(false);
    const policyScrollRef = useRef<HTMLDivElement>(null);

    const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
        const element = e.currentTarget;
        // Check if scrolled to bottom with small tolerance
        const atBottom = Math.abs(element.scrollHeight - element.scrollTop - element.clientHeight) < 5;
        if (atBottom) {
            setCanAcceptPrivacy(true);
        }
    };

    const handleAccept = () => {
        onAccept();
    };

    if (!isOpen) return null;

    return (
        <div className="modal open" aria-hidden={!isOpen} role="dialog" aria-labelledby="privacy-modal-title">
            <div className="modal-content max-w-2xl w-full mx-4">
                <div className="modal-header">
                    <h2 id="privacy-modal-title">Privacy & User Agreement</h2>
                    <button className="modal-close" onClick={onClose} aria-label="Close modal">×</button>
                </div>
                <div className="modal-body">
                    <div
                        className="policy-scroll bg-surface-1 p-6 rounded-lg border border-border mb-4 max-h-[60vh] overflow-y-auto"
                        id="privacy-policy-scroll"
                        tabIndex={0}
                        aria-label="AI Assistant disclaimer - scroll to read full text before accepting"
                        onScroll={handleScroll}
                        ref={policyScrollRef}
                    >
                        <h2 className="text-xl font-bold mb-4">AI Assistant Disclaimer and User Acknowledgment</h2>
                        <p className="mb-4">Before using the AI Assistant, you must read and acknowledge the following:</p>
                        <p className="text-xs text-text-secondary mt-4">By interacting with the AI, you agree to the storing of conversation history associated with your account. You can delete this history at any time in <a href="/settings" className="text-primary hover:underline">Settings</a>. Please review our <a href="/terms" className="text-primary hover:underline">Terms of Service</a> and <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>.</p>

                        <h3 className="text-lg font-semibold mt-4 mb-2">1. Nature of the AI Assistant</h3>
                        <p className="mb-2">The AI Assistant provides direct, unrestricted access to configured Large Language Models (LLMs) using environment-based model routing.</p>
                        <ul className="list-disc pl-5 mb-4 space-y-1">
                            <li>Free-tier default model: <strong>gpt-oss-120b</strong></li>
                            <li>Paid-tier default model: <strong>gemini-2.5-flash</strong></li>
                            <li>If paid premium capacity is exhausted, requests automatically fall back to <strong>gpt-oss-120b</strong> with explicit in-product messaging.</li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2">2. No Financial Advice</h3>
                        <p className="mb-2">The AI Assistant:</p>
                        <ul className="list-disc pl-5 mb-4 space-y-1">
                            <li><strong>IS NOT</strong> a financial advisor</li>
                            <li><strong>IS NOT</strong> an investment advisor</li>
                            <li><strong>IS NOT</strong> a tax advisor</li>
                            <li><strong>IS NOT</strong> a legal advisor</li>
                            <li><strong>DOES NOT</strong> provide financial, investment, tax, or legal advice</li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2">3. No Endorsement or Verification</h3>
                        <ul className="list-disc pl-5 mb-4 space-y-1">
                            <li>Responses generated by the AI Assistant are <strong>NOT</strong> endorsed by Intellifide, LLC</li>
                            <li>Responses are <strong>NOT</strong> verified for accuracy</li>
                            <li>Responses may be <strong>inaccurate, incomplete, or inappropriate</strong></li>
                            <li>Responses may contain <strong>errors, biases, or outdated information</strong></li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2">4. User Responsibility</h3>
                        <p className="mb-2">You acknowledge and agree that:</p>
                        <ul className="list-disc pl-5 mb-4 space-y-1">
                            <li>You will <strong>NOT</strong> rely on AI Assistant responses for financial decisions</li>
                            <li>You will <strong>NOT</strong> use AI Assistant responses as investment, tax, or legal advice</li>
                            <li>You will <strong>consult qualified professionals</strong> for financial, investment, tax, or legal matters</li>
                            <li>You understand that <strong>all investments carry risk</strong></li>
                            <li>You use the AI Assistant <strong>at your own risk</strong></li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2">5. No Liability</h3>
                        <p className="mb-2">Intellifide, LLC:</p>
                        <ul className="list-disc pl-5 mb-4 space-y-1">
                            <li><strong>DISCLAIMS ALL LIABILITY</strong> for decisions you make based on AI Assistant responses</li>
                            <li><strong>DISCLAIMS ALL LIABILITY</strong> for any losses or damages resulting from use of AI Assistant</li>
                            <li><strong>DISCLAIMS ALL WARRANTIES</strong> regarding accuracy, completeness, or appropriateness of AI responses</li>
                            <li><strong>IS NOT RESPONSIBLE</strong> for the content, accuracy, or appropriateness of AI-generated responses</li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2">6. Unrestricted Access</h3>
                        <p className="mb-2">The AI Assistant provides <strong>unrestricted, unfiltered access</strong> to third-party LLMs. Intellifide, LLC:</p>
                        <ul className="list-disc pl-5 mb-4 space-y-1">
                            <li>Does <strong>NOT</strong> filter or restrict user queries</li>
                            <li>Does <strong>NOT</strong> filter or restrict AI responses</li>
                            <li>Does <strong>NOT</strong> review or approve AI responses before display</li>
                            <li>Provides direct pass-through to third-party LLM services</li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2">7. Third-Party Services</h3>
                        <p className="mb-2">The AI Assistant uses third-party LLM services. Your use of these services is subject to:</p>
                        <label htmlFor="ai-consent" className="text-sm text-gray-400">
                            I understand that my data will be processed by third-party AI providers (Google Gemini) and agree to the &quot;AI Terms of Service&quot; and &quot;Privacy Policy&quot;.
                        </label>            <ul className="list-disc pl-5 mb-4 space-y-1">
                            <li>Intellifide, LLC is not responsible for third-party LLM provider actions or policies</li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2">8. Usage Metering and Reset Date Notice</h3>
                        <ul className="list-disc pl-5 mb-4 space-y-1">
                            <li>AI usage is displayed as <strong>AI usage this period</strong>.</li>
                            <li>The product displays a reset date tied to your billing-cycle anniversary period.</li>
                            <li>Usage limits are enforced by backend token-based metering.</li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2">9. Acknowledgment and Acceptance</h3>
                        <p className="mb-2">By clicking &quot;I Agree&quot; or &quot;Accept&quot; below, you acknowledge that:</p>
                        <ul className="list-disc pl-5 mb-4 space-y-1">
                            <li>You have read and understood this disclaimer</li>
                            <li>You understand the limitations and risks of using the AI Assistant</li>
                            <li>You understand model routing and paid-capacity fallback behavior described above</li>
                            <li>You agree not to rely on AI Assistant responses for financial decisions</li>
                            <li>You agree to consult qualified professionals for financial, investment, tax, or legal matters</li>
                            <li>You accept all risks associated with using the AI Assistant</li>
                            <li>You release Intellifide, LLC from all liability related to your use of the AI Assistant</li>
                        </ul>
                    </div>

                    <p id="privacy-scroll-hint" className="policy-scroll-footer text-center text-sm text-text-muted mb-4 opacity-75">
                        {canAcceptPrivacy ? 'You can now accept and continue.' : 'Scroll to the bottom to enable “Accept & Continue”.'}
                    </p>

                    <div className="flex gap-4">
                        <button
                            id="accept-privacy"
                            className="btn btn-primary flex-1"
                            disabled={!canAcceptPrivacy}
                            aria-disabled={!canAcceptPrivacy}
                            onClick={handleAccept}
                        >
                            Accept & Continue
                        </button>
                        <button
                            id="deny-privacy"
                            className="btn btn-outline flex-1"
                            onClick={onClose}
                        >
                            Cancel
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};
