/*
 * Copyright (c) 2026 Intellifide, LLC.
 * Licensed under PolyForm Noncommercial License 1.0.0.
 * See "PolyForm-Noncommercial-1.0.0.txt" for full text.
 *
 * COMMUNITY RIGHTS:
 * - You CAN modify this code for personal use.
 * - You CAN build and share widgets/plugins for the ecosystem.
 *
 * RESTRICTIONS:
 * - You CANNOT resell, repackage, or distribute this application for a fee.
 * - You CANNOT use this application for commercial enterprise purposes.
 */

/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/sync_feature_registry.py
 */

export const featureKeys = [
  'accounts.cex',
  'accounts.manual',
  'accounts.plaid',
  'accounts.web3',
  'ai.cloud',
  'assets.manual',
  'budgets.advanced',
  'family.tracking',
  'investment.aggregation',
  'marketplace.preview',
  'marketplace.publish',
  'recurring.detection',
] as const
export type FeatureKey = (typeof featureKeys)[number]

export const accountTypes = [
  'cex',
  'manual',
  'plaid',
  'web3',
] as const
export type AccountType = (typeof accountTypes)[number]

export type TierSlug = 'free' | 'essential' | 'pro' | 'ultimate'
export enum Tier {
  FREE = 0,
  ESSENTIAL = 1,
  PRO = 2,
  ULTIMATE = 3,
}

export const tierOrder: Record<TierSlug, number> = {
  free: 0,
  essential: 1,
  pro: 2,
  ultimate: 3,
}

export const featureRequirements: Record<FeatureKey, { tier: Tier; previewEnabled: boolean; description: string }> = {
  'accounts.cex': { tier: Tier.FREE, previewEnabled: false, description: "CEX account connection limits" },
  'accounts.manual': { tier: Tier.FREE, previewEnabled: false, description: "Manual account tracking limits" },
  'accounts.plaid': { tier: Tier.FREE, previewEnabled: false, description: "Plaid-connected account limits" },
  'accounts.web3': { tier: Tier.FREE, previewEnabled: false, description: "Web3 wallet connection limits" },
  'ai.cloud': { tier: Tier.FREE, previewEnabled: true, description: "Cloud AI chat interface with RAG context (Tiered limits: Free 10/day, Essential 30/day, Pro 40/day)" },
  'assets.manual': { tier: Tier.FREE, previewEnabled: false, description: "Manual asset tracking for non-API assets" },
  'budgets.advanced': { tier: Tier.FREE, previewEnabled: false, description: "Advanced budgets with rollover, threshold alerts, budget-vs-actual" },
  'family.tracking': { tier: Tier.ULTIMATE, previewEnabled: true, description: "Family/couple net worth tracking and account assignment" },
  'investment.aggregation': { tier: Tier.FREE, previewEnabled: false, description: "Investment account aggregation via Plaid Investments API" },
  'marketplace.preview': { tier: Tier.PRO, previewEnabled: false, description: "Access to install and use marketplace widgets" },
  'marketplace.publish': { tier: Tier.PRO, previewEnabled: false, description: "Ability to publish widgets to marketplace (Requires Developer Agreement)" },
  'recurring.detection': { tier: Tier.FREE, previewEnabled: false, description: "Automated detection of recurring transactions" },
}

export const accountLimits: Record<AccountType, Record<TierSlug, number>> = {
  'cex': { free: 1, essential: 1, pro: 3, ultimate: 5 },
  'manual': { free: 5, essential: 10, pro: 20, ultimate: 50 },
  'plaid': { free: 3, essential: 5, pro: 10, ultimate: 40 },
  'web3': { free: 1, essential: 1, pro: 2, ultimate: 8 },
}

export const accountLimitsByTier: Record<TierSlug, Record<AccountType, number>> = {
  free: { 'cex': 1, 'manual': 5, 'plaid': 3, 'web3': 1 },
  essential: { 'cex': 1, 'manual': 10, 'plaid': 5, 'web3': 1 },
  pro: { 'cex': 3, 'manual': 20, 'plaid': 10, 'web3': 2 },
  ultimate: { 'cex': 5, 'manual': 50, 'plaid': 40, 'web3': 8 },
}

export const normalizeTierSlug = (value?: string | null): TierSlug | null => {
  if (!value) return null
  const normalized = value.toLowerCase()
  if (normalized.includes('ultimate')) return 'ultimate'
  if (normalized.includes('pro')) return 'pro'
  if (normalized.includes('essential')) return 'essential'
  if (normalized.includes('free')) return 'free'
  return null
}

const tierEnumFromSlug = (tier: TierSlug): Tier => {
  switch (tier) {
    case 'ultimate':
      return Tier.ULTIMATE
    case 'pro':
      return Tier.PRO
    case 'essential':
      return Tier.ESSENTIAL
    default:
      return Tier.FREE
  }
}

export const tierSlugFromPlan = (value?: string | null): TierSlug => {
  return normalizeTierSlug(value) ?? 'free'
}

export const tierFromPlan = (value?: string | null): Tier => {
  return tierEnumFromSlug(tierSlugFromPlan(value))
}

const resolveTierEnum = (tier: Tier | TierSlug): Tier => {
  return typeof tier === 'string' ? tierEnumFromSlug(tier) : tier
}

export const canUseFeature = (featureKey: FeatureKey, userTier: Tier | TierSlug): boolean => {
  const requirement = featureRequirements[featureKey]
  if (!requirement) return false
  return resolveTierEnum(userTier) >= requirement.tier
}

export const canPreviewFeature = (featureKey: FeatureKey): boolean => {
  return Boolean(featureRequirements[featureKey]?.previewEnabled)
}

export const isPremiumFeature = (featureKey: FeatureKey): boolean => {
  return featureRequirements[featureKey]?.tier !== Tier.FREE
}

