/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/sync_feature_registry.py
 */

export const featureKeys = [
  'accounts.cex',
  'accounts.investment',
  'accounts.manual',
  'accounts.traditional',
  'accounts.web3',
  'ai.cloud',
  'assets.manual',
  'budgets.advanced',
  'budgets.basic',
  'family.tracking',
  'investment.aggregation',
  'marketplace.preview',
  'marketplace.publish',
  'recurring.detection',
  'reporting.advanced',
  'reporting.basic',
] as const
export type FeatureKey = (typeof featureKeys)[number]

export const accountTypes = [
  'cex',
  'investment',
  'manual',
  'traditional',
  'web3',
] as const
export type AccountType = (typeof accountTypes)[number]

export type TierSlug = 'free' | 'essential' | 'pro' | 'ultimate'
export enum Tier {
  FREE = 0,
  ESSENTIAL = 1,
  PRO = 2,
  ULTIMATE = 3,
}

export const tierOrder: Record<TierSlug, number> = {
  free: 0,
  essential: 1,
  pro: 2,
  ultimate: 3,
}

export const featureRequirements: Record<FeatureKey, { tier: Tier; previewEnabled: boolean; description: string }> = {
  'accounts.cex': { tier: Tier.FREE, previewEnabled: false, description: "CEX account connection limits" },
  'accounts.investment': { tier: Tier.FREE, previewEnabled: false, description: "Investment account connection limits" },
  'accounts.manual': { tier: Tier.FREE, previewEnabled: false, description: "Manual account tracking limits" },
  'accounts.traditional': { tier: Tier.FREE, previewEnabled: false, description: "Traditional bank account connection limits" },
  'accounts.web3': { tier: Tier.FREE, previewEnabled: false, description: "Web3 wallet connection limits" },
  'ai.cloud': { tier: Tier.FREE, previewEnabled: true, description: "Cloud AI chat interface with RAG context (Tiered limits: Free 10/day, Essential 30/day, Pro 40/day)" },
  'assets.manual': { tier: Tier.FREE, previewEnabled: false, description: "Manual asset tracking for non-API assets" },
  'budgets.advanced': { tier: Tier.PRO, previewEnabled: true, description: "Advanced budgets with rollover, threshold alerts, budget-vs-actual" },
  'budgets.basic': { tier: Tier.FREE, previewEnabled: false, description: "Basic budget tracking and visualization" },
  'family.tracking': { tier: Tier.ULTIMATE, previewEnabled: true, description: "Family/couple net worth tracking and account assignment" },
  'investment.aggregation': { tier: Tier.PRO, previewEnabled: false, description: "Investment account aggregation via Plaid Investments API" },
  'marketplace.preview': { tier: Tier.PRO, previewEnabled: true, description: "Access to install and use marketplace widgets" },
  'marketplace.publish': { tier: Tier.FREE, previewEnabled: false, description: "Ability to publish widgets to marketplace (Requires Developer Agreement)" },
  'recurring.detection': { tier: Tier.FREE, previewEnabled: false, description: "Automated detection of recurring transactions" },
  'reporting.advanced': { tier: Tier.PRO, previewEnabled: true, description: "Advanced reporting and analytics" },
  'reporting.basic': { tier: Tier.FREE, previewEnabled: false, description: "Basic reporting and infographics" },
}

export const accountLimits: Record<AccountType, Record<TierSlug, number>> = {
  'cex': { free: 1, essential: 3, pro: 10, ultimate: 20 },
  'investment': { free: 1, essential: 2, pro: 5, ultimate: 20 },
  'manual': { free: 5, essential: 10, pro: 20, ultimate: 50 },
  'traditional': { free: 2, essential: 3, pro: 5, ultimate: 20 },
  'web3': { free: 1, essential: 1, pro: 5, ultimate: 20 },
}

export const accountLimitsByTier: Record<TierSlug, Record<AccountType, number>> = {
  free: { 'cex': 1, 'investment': 1, 'manual': 5, 'traditional': 2, 'web3': 1 },
  essential: { 'cex': 3, 'investment': 2, 'manual': 10, 'traditional': 3, 'web3': 1 },
  pro: { 'cex': 10, 'investment': 5, 'manual': 20, 'traditional': 5, 'web3': 5 },
  ultimate: { 'cex': 20, 'investment': 20, 'manual': 50, 'traditional': 20, 'web3': 20 },
}

export const normalizeTierSlug = (value?: string | null): TierSlug | null => {
  if (!value) return null
  const normalized = value.toLowerCase()
  if (normalized.includes('ultimate')) return 'ultimate'
  if (normalized.includes('pro')) return 'pro'
  if (normalized.includes('essential')) return 'essential'
  if (normalized.includes('free')) return 'free'
  return null
}

const tierEnumFromSlug = (tier: TierSlug): Tier => {
  switch (tier) {
    case 'ultimate':
      return Tier.ULTIMATE
    case 'pro':
      return Tier.PRO
    case 'essential':
      return Tier.ESSENTIAL
    default:
      return Tier.FREE
  }
}

export const tierSlugFromPlan = (value?: string | null): TierSlug => {
  return normalizeTierSlug(value) ?? 'free'
}

export const tierFromPlan = (value?: string | null): Tier => {
  return tierEnumFromSlug(tierSlugFromPlan(value))
}

const resolveTierEnum = (tier: Tier | TierSlug): Tier => {
  return typeof tier === 'string' ? tierEnumFromSlug(tier) : tier
}

export const canUseFeature = (featureKey: FeatureKey, userTier: Tier | TierSlug): boolean => {
  const requirement = featureRequirements[featureKey]
  if (!requirement) return false
  return resolveTierEnum(userTier) >= requirement.tier
}

export const canPreviewFeature = (featureKey: FeatureKey): boolean => {
  return Boolean(featureRequirements[featureKey]?.previewEnabled)
}

export const isPremiumFeature = (featureKey: FeatureKey): boolean => {
  return featureRequirements[featureKey]?.tier !== Tier.FREE
}

