"""Remove priority from support tickets

Revision ID: 09510e76e5e9
Revises: eb8b37b8b170
Create Date: 2025-12-09 21:42:14.724560

"""
# Updated 2025-12-10 22:20 CST by ChatGPT - remove unused import
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '09510e76e5e9'
down_revision: Union[str, None] = 'eb8b37b8b170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('audit_log',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('actor_uid', sa.String(length=128), nullable=False),
    # sa.Column('target_uid', sa.String(length=128), nullable=True),
    # sa.Column('action', sa.String(length=128), nullable=False),
    # sa.Column('source', sa.String(length=32), nullable=False, comment='frontend|backend|workflow'),
    # sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    # sa.Column('archived', sa.Boolean(), nullable=False),
    # sa.CheckConstraint("source IN ('frontend', 'backend', 'workflow')", name='ck_audit_log_source'),
    # sa.PrimaryKeyConstraint('id'),
    # schema='audit'
    # )
    # op.create_table('feature_preview',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('uid', sa.String(length=128), nullable=False),
    # sa.Column('feature_key', sa.String(length=128), nullable=False),
    # sa.Column('tier', sa.String(length=32), nullable=False),
    # sa.Column('action', sa.String(length=64), nullable=False),
    # sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    # sa.Column('archived', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # schema='audit'
    # )
    # op.create_table('llm_logs',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('uid', sa.String(length=128), nullable=False),
    # sa.Column('model', sa.String(length=64), nullable=False),
    # sa.Column('encrypted_prompt', postgresql.BYTEA(), nullable=False),
    # sa.Column('encrypted_response', postgresql.BYTEA(), nullable=False),
    # sa.Column('tokens', sa.Integer(), nullable=False),
    # sa.Column('user_dek_ref', sa.String(length=256), nullable=False),
    # sa.Column('archived', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # schema='audit'
    # )
    # op.create_table('support_portal_actions',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('agent_id', sa.UUID(), nullable=False),
    # sa.Column('agent_company_id', sa.String(length=32), nullable=False),
    # sa.Column('agent_name', sa.String(length=256), nullable=False),
    # sa.Column('ticket_id', sa.String(length=128), nullable=False),
    # sa.Column('customer_uid', sa.String(length=128), nullable=True),
    # sa.Column('action_type', sa.String(length=64), nullable=False),
    # sa.Column('action_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    # sa.Column('ip_address', sa.String(length=45), nullable=True),
    # sa.Column('archived', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # schema='audit'
    # )
    op.drop_column('support_tickets', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('priority', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
