"""generalize_local_notification

Revision ID: 182cbabe8e5e
Revises: 6e4cf2c1b4af
Create Date: 2025-12-13 19:26:00.117747

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "182cbabe8e5e"
down_revision: str | None = "6e4cf2c1b4af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Audit tables already exist, skipping creation.
    op.add_column(
        "local_notifications", sa.Column("title", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "local_notifications",
        sa.Column("is_read", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.alter_column(
        "local_notifications", "ticket_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "local_notifications",
        "event_key",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "local_notifications",
        "event_key",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "local_notifications", "ticket_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("local_notifications", "is_read")
    op.drop_column("local_notifications", "title")
    op.drop_column("local_notifications", "is_read")
    op.drop_column("local_notifications", "title")
    # op.drop_table('audit_log', schema='audit') # Skipped
    # ### end Alembic commands ###
