"""Add UserSession model

Revision ID: 208abc056f84
Revises: 4af12d04d3ec
Create Date: 2026-01-20 12:16:03.750438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208abc056f84'
down_revision: Union[str, None] = '4af12d04d3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=False),
    sa.Column('iat', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_iat'), 'user_sessions', ['iat'], unique=False)
    op.create_index(op.f('ix_user_sessions_uid'), 'user_sessions', ['uid'], unique=False)
    op.alter_column('household_invites', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='pending|accepted|declined|expired',
               existing_comment='pending|accepted|expired',
               existing_nullable=False)
    op.alter_column('household_invites', 'can_view_household',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('support_portal_actions', 'agent_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=128),
               existing_nullable=False,
               schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_portal_actions', 'agent_id',
               existing_type=sa.String(length=128),
               type_=sa.UUID(),
               existing_nullable=False,
               schema='audit')
    op.alter_column('household_invites', 'can_view_household',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('household_invites', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='pending|accepted|expired',
               existing_comment='pending|accepted|declined|expired',
               existing_nullable=False)
    op.drop_index(op.f('ix_user_sessions_uid'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_iat'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
