"""add can_view_household to invite

Revision ID: 2569d140160b
Revises: a1b2c3d4e5f6
Create Date: 2026-01-17 23:15:36.252140

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2569d140160b'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('household_invites', sa.Column('can_view_household', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household_invites', 'can_view_household')
    # ### end Alembic commands ###
