"""Add assigned_member_uid and custom_label to accounts

Revision ID: 328a88a1e3b3
Revises: 932d6d869b7e
Create Date: 2025-12-26 00:51:50.920534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '328a88a1e3b3'
down_revision: Union[str, None] = '932d6d869b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('audit_log',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('actor_uid', sa.String(length=128), nullable=False),
    # sa.Column('target_uid', sa.String(length=128), nullable=True),
    # sa.Column('action', sa.String(length=128), nullable=False),
    # sa.Column('source', sa.String(length=32), nullable=False, comment='frontend|backend|workflow'),
    # sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    # sa.Column('archived', sa.Boolean(), nullable=False),
    # sa.CheckConstraint("source IN ('frontend', 'backend', 'workflow')", name='ck_audit_log_source'),
    # sa.PrimaryKeyConstraint('id'),
    # schema='audit'
    # )
    # op.create_table('feature_preview',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('uid', sa.String(length=128), nullable=False),
    # sa.Column('feature_key', sa.String(length=128), nullable=False),
    # sa.Column('tier', sa.String(length=32), nullable=False),
    # sa.Column('action', sa.String(length=64), nullable=False),
    # sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    # sa.Column('archived', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # schema='audit'
    # )
    # op.create_table('llm_logs',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('uid', sa.String(length=128), nullable=False),
    # sa.Column('model', sa.String(length=64), nullable=False),
    # sa.Column('encrypted_prompt', postgresql.BYTEA(), nullable=False),
    # sa.Column('encrypted_response', postgresql.BYTEA(), nullable=False),
    # sa.Column('tokens', sa.Integer(), nullable=False),
    # sa.Column('user_dek_ref', sa.String(length=256), nullable=False),
    # sa.Column('archived', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # schema='audit'
    # )
    # op.create_table('support_portal_actions',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('agent_id', sa.String(length=128), nullable=False),
    # sa.Column('agent_company_id', sa.String(length=32), nullable=False),
    # sa.Column('agent_name', sa.String(length=256), nullable=False),
    # sa.Column('ticket_id', sa.String(length=128), nullable=False),
    # sa.Column('customer_uid', sa.String(length=128), nullable=True),
    # sa.Column('action_type', sa.String(length=64), nullable=False),
    # sa.Column('action_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    # sa.Column('ip_address', sa.String(length=45), nullable=True),
    # sa.Column('archived', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # schema='audit'
    # )
    op.add_column('accounts', sa.Column('assigned_member_uid', sa.String(length=128), nullable=True))
    op.add_column('accounts', sa.Column('custom_label', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'custom_label')
    op.drop_column('accounts', 'assigned_member_uid')
    op.drop_table('support_portal_actions', schema='audit')
    op.drop_table('llm_logs', schema='audit')
    op.drop_table('feature_preview', schema='audit')
    op.drop_table('audit_log', schema='audit')
    # ### end Alembic commands ###
