"""Add Email MFA fields

Revision ID: 3ec96be2cade
Revises: eb7d92fa3183
Create Date: 2025-12-18 20:41:33.773465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ec96be2cade'
down_revision: Union[str, None] = 'eb7d92fa3183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_method', sa.String(length=16), nullable=True, comment='totp|email|sms'))
    op.add_column('users', sa.Column('email_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('email_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'email_otp_expires_at')
    op.drop_column('users', 'email_otp')
    op.drop_column('users', 'mfa_method')
    # ### end Alembic commands ###
