"""add_data_sharing_consent

Revision ID: 4af12d04d3ec
Revises: 8b6f2a1c4d7e
Create Date: 2026-01-19 23:59:16.744556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4af12d04d3ec'
down_revision: Union[str, None] = '8b6f2a1c4d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data_sharing_consent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data_sharing_consent')
    # ### end Alembic commands ###
