"""Add plaid cursor and sync status

Revision ID: b054a13abe31
Revises: 182cbabe8e5e
Create Date: 2025-12-18 19:36:06.691963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b054a13abe31'
down_revision: Union[str, None] = '182cbabe8e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('plaid_next_cursor', sa.String(length=512), nullable=True))
    op.add_column('accounts', sa.Column('sync_status', sa.String(length=32), nullable=True))
    op.add_column('accounts', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('local_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('accounts', 'last_synced_at')
    op.drop_column('accounts', 'sync_status')
    op.drop_column('accounts', 'plaid_next_cursor')
    op.drop_table('support_portal_actions', schema='audit')
    op.drop_table('llm_logs', schema='audit')
    op.drop_table('feature_preview', schema='audit')
    op.drop_table('audit_log', schema='audit')
    # ### end Alembic commands ###
