"""Add unique constraint to UserSession

Revision ID: d2863d2356f2
Revises: 208abc056f84
Create Date: 2026-01-20 12:16:37.060822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2863d2356f2'
down_revision: Union[str, None] = '208abc056f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_session_uid_iat', 'user_sessions', ['uid', 'iat'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_session_uid_iat', 'user_sessions', type_='unique')
    # ### end Alembic commands ###
