"""Add user status and sync columns

Revision ID: d93c9f819c01
Revises: 3ec96be2cade
Create Date: 2025-12-19 12:44:32.189820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd93c9f819c01'
down_revision: Union[str, None] = '3ec96be2cade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Tables handled manually or previously existing
    # op.create_table('audit_log', ...)
    # op.create_table('feature_preview', ...)
    # op.create_table('llm_logs', ...)
    # op.create_table('support_portal_actions', ...)
    # op.create_table('category_rules', ...)
    
    op.add_column('users', sa.Column('status', sa.String(length=32), server_default='pending_verification', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    
    # op.drop_table('category_rules')
    # op.drop_table('support_portal_actions', schema='audit')
    # op.drop_table('llm_logs', schema='audit')
    # op.drop_table('feature_preview', schema='audit')
    # op.drop_table('audit_log', schema='audit')
    # ### end Alembic commands ###
