"""Initial schema

Revision ID: db65f46961a0
Revises:
Create Date: 2025-12-08 17:58:19.164689

"""

# Updated 2025-12-08 17:58 CST by ChatGPT
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db65f46961a0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS audit")
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_uid", sa.String(length=128), nullable=False),
        sa.Column("target_uid", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column(
            "source",
            sa.String(length=32),
            nullable=False,
            comment="frontend|backend|workflow",
        ),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "source IN ('frontend', 'backend', 'workflow')", name="ck_audit_log_source"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="audit",
    )
    op.create_table(
        "feature_preview",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uid", sa.String(length=128), nullable=False),
        sa.Column("feature_key", sa.String(length=128), nullable=False),
        sa.Column("tier", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="audit",
    )
    op.create_table(
        "llm_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uid", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("encrypted_prompt", postgresql.BYTEA(), nullable=False),
        sa.Column("encrypted_response", postgresql.BYTEA(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("user_dek_ref", sa.String(length=256), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="audit",
    )
    op.create_table(
        "support_portal_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("agent_company_id", sa.String(length=32), nullable=False),
        sa.Column("agent_name", sa.String(length=256), nullable=False),
        sa.Column("ticket_id", sa.String(length=128), nullable=False),
        sa.Column("customer_uid", sa.String(length=128), nullable=True),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column(
            "action_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="audit",
    )
    op.alter_column(
        "accounts",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "accounts", "account_type", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    op.alter_column(
        "accounts",
        "balance",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "accounts",
        "currency",
        existing_type=sa.VARCHAR(length=3),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_constraint("accounts_uid_fkey", "accounts", type_="foreignkey")
    op.create_foreign_key(None, "accounts", "users", ["uid"], ["uid"])
    op.alter_column(
        "ai_settings",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_settings",
        "provider",
        existing_type=sa.VARCHAR(length=32),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_settings",
        "model_id",
        existing_type=sa.VARCHAR(length=64),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint("ai_settings_uid_key", "ai_settings", type_="unique")
    op.create_unique_constraint("uq_ai_settings_uid", "ai_settings", ["uid"])
    op.alter_column(
        "developer_payouts",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "developer_payouts",
        "gross_revenue",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "developer_payouts",
        "payout_status",
        existing_type=sa.VARCHAR(length=32),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        "developer_payouts_month_dev_uid_key", "developer_payouts", type_="unique"
    )
    op.create_unique_constraint(
        "uq_payout_month_dev", "developer_payouts", ["month", "dev_uid"]
    )
    op.drop_constraint("developers_uid_fkey", "developers", type_="foreignkey")
    op.create_foreign_key(None, "developers", "users", ["uid"], ["uid"])
    op.alter_column(
        "ledger_hot_essential",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ledger_hot_essential",
        "currency",
        existing_type=sa.VARCHAR(length=3),
        server_default=None,
        existing_nullable=False,
    )
    op.create_foreign_key(
        None, "ledger_hot_essential", "users", ["uid"], ["uid"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "ledger_hot_essential",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "ledger_hot_free",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ledger_hot_free",
        "currency",
        existing_type=sa.VARCHAR(length=3),
        server_default=None,
        existing_nullable=False,
    )
    op.create_foreign_key(
        None, "ledger_hot_free", "accounts", ["account_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "ledger_hot_free", "users", ["uid"], ["uid"], ondelete="CASCADE"
    )
    op.alter_column(
        "manual_assets",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "notification_preferences",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "notification_preferences",
        "channel_email",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        nullable=False,
    )
    op.alter_column(
        "notification_preferences",
        "channel_sms",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        nullable=False,
    )
    op.drop_constraint(
        "notification_preferences_uid_event_key_key",
        "notification_preferences",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_notification_event", "notification_preferences", ["uid", "event_key"]
    )
    op.alter_column(
        "payments",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "plan",
        existing_type=sa.VARCHAR(length=32),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "status",
        existing_type=sa.VARCHAR(length=32),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "ai_quota_used",
        existing_type=sa.INTEGER(),
        server_default=None,
        nullable=True,
    )
    op.drop_constraint("subscriptions_uid_key", "subscriptions", type_="unique")
    op.drop_constraint("subscriptions_uid_fkey", "subscriptions", type_="foreignkey")
    op.create_foreign_key(None, "subscriptions", "users", ["uid"], ["uid"])
    op.alter_column(
        "support_agents",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "support_agents",
        "active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "support_ticket_ratings",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        "support_ticket_ratings_ticket_id_key", "support_ticket_ratings", type_="unique"
    )
    op.create_unique_constraint(
        "uq_ticket_rating_ticket", "support_ticket_ratings", ["ticket_id"]
    )
    op.create_foreign_key(
        None,
        "support_ticket_ratings",
        "support_agents",
        ["agent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "transactions",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "currency",
        existing_type=sa.VARCHAR(length=3),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=32),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "theme_pref",
        existing_type=sa.VARCHAR(length=32),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "currency_pref",
        existing_type=sa.VARCHAR(length=3),
        server_default=None,
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "currency_pref",
        existing_type=sa.VARCHAR(length=3),
        server_default=sa.text("'USD'::character varying"),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "theme_pref",
        existing_type=sa.VARCHAR(length=32),
        server_default=sa.text("'glass'::character varying"),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=32),
        server_default=sa.text("'user'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "currency",
        existing_type=sa.VARCHAR(length=3),
        server_default=sa.text("'USD'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "support_ticket_ratings", type_="foreignkey")
    op.drop_constraint(
        "uq_ticket_rating_ticket", "support_ticket_ratings", type_="unique"
    )
    op.create_unique_constraint(
        "support_ticket_ratings_ticket_id_key", "support_ticket_ratings", ["ticket_id"]
    )
    op.alter_column(
        "support_ticket_ratings",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "support_agents",
        "active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "support_agents",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "subscriptions", type_="foreignkey")
    op.create_foreign_key(
        "subscriptions_uid_fkey",
        "subscriptions",
        "users",
        ["uid"],
        ["uid"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("subscriptions_uid_key", "subscriptions", ["uid"])
    op.alter_column(
        "subscriptions",
        "ai_quota_used",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "status",
        existing_type=sa.VARCHAR(length=32),
        server_default=sa.text("'active'::character varying"),
        nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "plan",
        existing_type=sa.VARCHAR(length=32),
        server_default=sa.text("'free'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "payments",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_constraint(
        "uq_notification_event", "notification_preferences", type_="unique"
    )
    op.create_unique_constraint(
        "notification_preferences_uid_event_key_key",
        "notification_preferences",
        ["uid", "event_key"],
    )
    op.alter_column(
        "notification_preferences",
        "channel_sms",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        nullable=True,
    )
    op.alter_column(
        "notification_preferences",
        "channel_email",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        nullable=True,
    )
    op.alter_column(
        "notification_preferences",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "manual_assets",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "ledger_hot_free", type_="foreignkey")
    op.drop_constraint(None, "ledger_hot_free", type_="foreignkey")
    op.alter_column(
        "ledger_hot_free",
        "currency",
        existing_type=sa.VARCHAR(length=3),
        server_default=sa.text("'USD'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "ledger_hot_free",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "ledger_hot_essential", type_="foreignkey")
    op.drop_constraint(None, "ledger_hot_essential", type_="foreignkey")
    op.alter_column(
        "ledger_hot_essential",
        "currency",
        existing_type=sa.VARCHAR(length=3),
        server_default=sa.text("'USD'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "ledger_hot_essential",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "developers", type_="foreignkey")
    op.create_foreign_key(
        "developers_uid_fkey",
        "developers",
        "users",
        ["uid"],
        ["uid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_payout_month_dev", "developer_payouts", type_="unique")
    op.create_unique_constraint(
        "developer_payouts_month_dev_uid_key", "developer_payouts", ["month", "dev_uid"]
    )
    op.alter_column(
        "developer_payouts",
        "payout_status",
        existing_type=sa.VARCHAR(length=32),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "developer_payouts",
        "gross_revenue",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "developer_payouts",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_constraint("uq_ai_settings_uid", "ai_settings", type_="unique")
    op.create_unique_constraint("ai_settings_uid_key", "ai_settings", ["uid"])
    op.alter_column(
        "ai_settings",
        "model_id",
        existing_type=sa.VARCHAR(length=64),
        server_default=sa.text("'gemini-2.5-flash'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_settings",
        "provider",
        existing_type=sa.VARCHAR(length=32),
        server_default=sa.text("'vertex-ai'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_settings",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.create_foreign_key(
        "accounts_uid_fkey", "accounts", "users", ["uid"], ["uid"], ondelete="CASCADE"
    )
    op.alter_column(
        "accounts",
        "currency",
        existing_type=sa.VARCHAR(length=3),
        server_default=sa.text("'USD'::character varying"),
        existing_nullable=True,
    )
    op.alter_column(
        "accounts",
        "balance",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        server_default=sa.text("0"),
        existing_nullable=True,
    )
    op.alter_column(
        "accounts", "account_type", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    op.alter_column(
        "accounts",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_table("support_portal_actions", schema="audit")
    op.drop_table("llm_logs", schema="audit")
    op.drop_table("feature_preview", schema="audit")
    op.drop_table("audit_log", schema="audit")
    # ### end Alembic commands ###
