#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 3 ]]; then
  echo "Usage: $0 <gcp-project-id> <output-env-file> <ENV_KEY=secret-name> [ENV_KEY=secret-name ...]" >&2
  exit 1
fi

PROJECT_ID="$1"
OUTPUT_FILE="$2"
shift 2

mkdir -p "$(dirname "$OUTPUT_FILE")"
TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

{
  echo "# Generated by mobile/scripts/materialize-mobile-env-from-gcp.sh"
  echo "# Project: ${PROJECT_ID}"
} > "$TMP_FILE"

for mapping in "$@"; do
  if [[ "$mapping" != *=* ]]; then
    echo "Invalid mapping '$mapping'. Expected ENV_KEY=secret-name" >&2
    exit 1
  fi

  env_key="${mapping%%=*}"
  secret_name="${mapping#*=}"

  if [[ -z "$env_key" || -z "$secret_name" ]]; then
    echo "Invalid mapping '$mapping'. Expected non-empty ENV_KEY and secret-name" >&2
    exit 1
  fi

  secret_value="$(gcloud secrets versions access latest --project="$PROJECT_ID" --secret="$secret_name")"
  escaped_value="$(printf '%s' "$secret_value" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
  printf '%s="%s"\n' "$env_key" "$escaped_value" >> "$TMP_FILE"
done

mv "$TMP_FILE" "$OUTPUT_FILE"
echo "Wrote env file: $OUTPUT_FILE"
