# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by scripts/sync_feature_registry.py
from __future__ import annotations

from enum import IntEnum
from typing import Any

TIER_ORDER = ('free', 'essential', 'pro', 'ultimate')

class Tier(IntEnum):
    FREE = 0
    ESSENTIAL = 1
    PRO = 2
    ULTIMATE = 3

feature_requirements: dict[str, dict[str, Any]] = {
    'accounts.cex': {
        'tier': Tier.FREE,
        'preview_enabled': False,
        'description': 'CEX account connection limits',
    },
    'accounts.investment': {
        'tier': Tier.FREE,
        'preview_enabled': False,
        'description': 'Investment account connection limits',
    },
    'accounts.manual': {
        'tier': Tier.FREE,
        'preview_enabled': False,
        'description': 'Manual account tracking limits',
    },
    'accounts.traditional': {
        'tier': Tier.FREE,
        'preview_enabled': False,
        'description': 'Traditional bank account connection limits',
    },
    'accounts.web3': {
        'tier': Tier.FREE,
        'preview_enabled': False,
        'description': 'Web3 wallet connection limits',
    },
    'ai.cloud': {
        'tier': Tier.FREE,
        'preview_enabled': True,
        'description': 'Cloud AI chat interface with RAG context (Tiered limits: Free 10/day, Essential 30/day, Pro 40/day)',
    },
    'assets.manual': {
        'tier': Tier.FREE,
        'preview_enabled': False,
        'description': 'Manual asset tracking for non-API assets',
    },
    'budgets.advanced': {
        'tier': Tier.PRO,
        'preview_enabled': True,
        'description': 'Advanced budgets with rollover, threshold alerts, budget-vs-actual',
    },
    'budgets.basic': {
        'tier': Tier.FREE,
        'preview_enabled': False,
        'description': 'Basic budget tracking and visualization',
    },
    'family.tracking': {
        'tier': Tier.ULTIMATE,
        'preview_enabled': True,
        'description': 'Family/couple net worth tracking and account assignment',
    },
    'investment.aggregation': {
        'tier': Tier.PRO,
        'preview_enabled': False,
        'description': 'Investment account aggregation via Plaid Investments API',
    },
    'marketplace.preview': {
        'tier': Tier.PRO,
        'preview_enabled': True,
        'description': 'Access to install and use marketplace widgets',
    },
    'marketplace.publish': {
        'tier': Tier.FREE,
        'preview_enabled': False,
        'description': 'Ability to publish widgets to marketplace (Requires Developer Agreement)',
    },
    'recurring.detection': {
        'tier': Tier.FREE,
        'preview_enabled': False,
        'description': 'Automated detection of recurring transactions',
    },
    'reporting.advanced': {
        'tier': Tier.PRO,
        'preview_enabled': True,
        'description': 'Advanced reporting and analytics',
    },
    'reporting.basic': {
        'tier': Tier.FREE,
        'preview_enabled': False,
        'description': 'Basic reporting and infographics',
    },
}

account_limits: dict[str, dict[str, int]] = {
    'cex': {'free': 1, 'essential': 3, 'pro': 10, 'ultimate': 20},
    'investment': {'free': 1, 'essential': 2, 'pro': 5, 'ultimate': 20},
    'manual': {'free': 5, 'essential': 10, 'pro': 20, 'ultimate': 50},
    'traditional': {'free': 2, 'essential': 3, 'pro': 5, 'ultimate': 20},
    'web3': {'free': 1, 'essential': 1, 'pro': 5, 'ultimate': 20},
}

account_limits_by_tier: dict[str, dict[str, int]] = {
    'free': {'cex': 1, 'investment': 1, 'manual': 5, 'traditional': 2, 'web3': 1},
    'essential': {'cex': 3, 'investment': 2, 'manual': 10, 'traditional': 3, 'web3': 1},
    'pro': {'cex': 10, 'investment': 5, 'manual': 20, 'traditional': 5, 'web3': 5},
    'ultimate': {'cex': 20, 'investment': 20, 'manual': 50, 'traditional': 20, 'web3': 20},
}

def tier_from_string(value: str | Tier | None) -> Tier:
    if isinstance(value, Tier):
        return value
    if not value:
        return Tier.FREE
    normalized = value.lower()
    if 'ultimate' in normalized:
        return Tier.ULTIMATE
    if 'pro' in normalized:
        return Tier.PRO
    if 'essential' in normalized:
        return Tier.ESSENTIAL
    return Tier.FREE

def get_required_tier(feature_key: str) -> Tier | None:
    entry = feature_requirements.get(feature_key)
    if not entry:
        return None
    return entry.get('tier') if isinstance(entry.get('tier'), Tier) else None

def can_use_feature(feature_key: str, user_tier: str | Tier | None) -> bool:
    entry = feature_requirements.get(feature_key)
    if not entry:
        return False
    required = entry.get('tier', Tier.FREE)
    return tier_from_string(user_tier) >= required

def can_preview_feature(feature_key: str) -> bool:
    entry = feature_requirements.get(feature_key)
    if not entry:
        return False
    return bool(entry.get('preview_enabled'))

def get_feature_description(feature_key: str) -> str:
    entry = feature_requirements.get(feature_key)
    if not entry:
        return ''
    return str(entry.get('description') or '')

