GRANT CONNECT ON DATABASE jualuma TO jualuma_user;
GRANT USAGE ON SCHEMA public TO jualuma_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jualuma_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jualuma_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO jualuma_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO jualuma_user;